# Generated by Django 5.2.17 on 2026-09-02 07:57

import datetime
import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "num_rounds",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "round_duration",
                    models.DurationField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                datetime.timedelta(seconds=1)
                            )
                        ]
                    ),
                ),
                (
                    "break_duration",
                    models.DurationField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                datetime.timedelta(0)
                            )
                        ]
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-start_time",),
                "indexes": [
                    models.Index(
                        fields=["status", "start_time"],
                        name="events_even_status_189ced_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("ready", "Ready"),
                            ("active", "Active"),
                            ("disconnected", "Disconnected"),
                            ("completed", "Completed"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("join_token_hash", models.CharField(max_length=256)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ("event", "number"),
            },
        ),
        migrations.CreateModel(
            name="Pair",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("room_id", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairs_as_a",
                        to="events.participant",
                    ),
                ),
                (
                    "participant_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairs_as_b",
                        to="events.participant",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairs",
                        to="events.round",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParticipantTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_tags",
                        to="events.participant",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_tags",
                        to="events.tag",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="participant",
            name="tags",
            field=models.ManyToManyField(
                related_name="participants",
                through="events.ParticipantTag",
                to="events.tag",
            ),
        ),
        migrations.AddIndex(
            model_name="round",
            index=models.Index(
                fields=["event", "status"], name="events_roun_event_i_43c9e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="round",
            index=models.Index(
                fields=["event", "starts_at"], name="events_roun_event_i_d5470e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.UniqueConstraint(
                fields=("event", "number"), name="uniq_round_number_per_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="round_ends_after_start",
            ),
        ),
        migrations.AddIndex(
            model_name="pair",
            index=models.Index(
                fields=["round", "status"], name="events_pair_round_i_dbaae2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pair",
            index=models.Index(
                fields=["participant_a", "round"], name="events_pair_partici_d42801_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pair",
            index=models.Index(
                fields=["participant_b", "round"], name="events_pair_partici_23b89c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pair",
            constraint=models.CheckConstraint(
                condition=models.Q(("participant_a__lt", models.F("participant_b"))),
                name="pair_participants_are_ordered_and_distinct",
            ),
        ),
        migrations.AddConstraint(
            model_name="pair",
            constraint=models.UniqueConstraint(
                fields=("round", "participant_a", "participant_b"),
                name="uniq_pair_per_round",
            ),
        ),
        migrations.AddIndex(
            model_name="participanttag",
            index=models.Index(
                fields=["tag", "participant"], name="events_part_tag_id_9b40c5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="participanttag",
            constraint=models.UniqueConstraint(
                fields=("participant", "tag"), name="uniq_participant_tag"
            ),
        ),
        migrations.AddIndex(
            model_name="participant",
            index=models.Index(
                fields=["event", "status"], name="events_part_event_i_b8180a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="participant",
            index=models.Index(
                fields=["event", "created_at"], name="events_part_event_i_1035f7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(
                fields=("event", "display_name"), name="uniq_participant_name_per_event"
            ),
        ),
    ]
