# Generated by Django 5.2.17 on 2026-09-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pair",
            name="pair_participants_are_ordered_and_distinct",
        ),
        migrations.AddConstraint(
            model_name="pair",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("participant_a", models.F("participant_b")), _negated=True
                ),
                name="pair_participants_are_distinct",
            ),
        ),
    ]
