# Generated by Django 5.2.17 on 2026-09-07 21:47

from django.db import migrations, models

import apps.events.models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_event_scoring_weights"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="scoring_weights",
            field=models.JSONField(default=apps.events.models._default_scoring_weights),
        ),
    ]
