# Generated by Django 5.2.17 on 2026-09-11 06:30

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_alter_event_scoring_weights"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatorActionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("pause", "Pause"),
                            ("resume", "Resume"),
                            ("extend", "Extend"),
                        ],
                        max_length=16,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "performed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operator_logs",
                        to="events.event",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operator_logs",
                        to="events.round",
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at"],
            },
        ),
    ]
