# Generated by Django 5.2.17 on 2026-09-11 04:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_event_state_machine"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="eventtransitionlog",
            new_name="events_even_event_i_bf42a7_idx",
            old_name="events_tlog_event_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="eventtransitionlog",
            new_name="events_even_is_comp_b94c2c_idx",
            old_name="events_tlog_complete_idx",
        ),
        migrations.RenameIndex(
            model_name="leaderlease",
            new_name="events_lead_lease_n_5ba517_idx",
            old_name="events_lead_lease_n_expires_idx",
        ),
    ]
