# Generated by Django 5.2.17 on 2026-09-20 17:10

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_pair_connection_time_ms_a_pair_connection_time_ms_b_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipantIncidentNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_notes",
                        to="events.event",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operator_incident_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_notes",
                        to="events.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DisconnectionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cause",
                    models.CharField(
                        choices=[
                            ("network", "خطای شبکه / Network"),
                            ("tab_closed", "بستن برگه / Tab Closed"),
                            ("permission_denied", "رد مجوز مدیا / Permission Denied"),
                        ],
                        db_index=True,
                        default="network",
                        max_length=32,
                    ),
                ),
                ("detail", models.TextField(blank=True, default="")),
                (
                    "disconnected_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("reconnected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disconnection_logs",
                        to="events.event",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disconnection_logs",
                        to="events.participant",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disconnection_logs",
                        to="events.round",
                    ),
                ),
            ],
            options={
                "ordering": ["-disconnected_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "disconnected_at"],
                        name="events_disc_event_i_daa6b4_idx",
                    ),
                    models.Index(
                        fields=["participant", "disconnected_at"],
                        name="events_disc_partici_fb7e4b_idx",
                    ),
                ],
            },
        ),
    ]
