# Generated by Django 5.2.17 on 2026-09-04 15:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_participant_join_token_metadata'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCheckLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('camera_working', models.BooleanField(default=False)),
                ('mic_working', models.BooleanField(default=False)),
                ('error_type', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('is_in_app_browser', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_check_logs', to='events.event')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_checks', to='events.participant')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
